spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsdown3.0?characterEncoding=UTF-8&serverTimezone=UTC
    username: gx_wlw
    password: gx_wlw_123
    driver-class-name: com.mysql.cj.jdbc.Driver