spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lsdown3.0?characterEncoding=UTF-8&serverTimezone=UTC
    username: develop
    password: develop2017
    driver-class-name: com.mysql.cj.jdbc.Driver